name: Force Close Pull Requests

on:
  pull_request:

jobs:
  close:
    runs-on: ubuntu-latest
    steps:
      - name: Close pull request
        uses: peter-evans/close-pull@v2
        with:
          comment: |
             Pull requests are not accepted.
             This is a blank repository, used for GitHub Discussions on the whole
             FreeNT Project.
             
             You are most likely looking to contribute to [OpenWindows](https://github.com/freent-project/openwindows),
             the [FreeNT Kernel](https://github.com/freent-project/freent), or the
             [`owboot`](https://github.com/freent-project/owboot) boot loader.
