name: Force Close Pull Requests

on:
  pull_request_target:
  pull_request:

jobs:
  close:
    runs-on: ubuntu-latest
    steps:
      - name: Close pull request
        uses: peter-evans/close-pull@v2
        with:
          comment: |
            I'm an NT Bot from Flossia. I work for and am named after the FreeNT Project.
            
            Contributions to this repository are not accepted. I'm so sorry. Anyways, this repository only provides our fourms.
            You can contribute to most FreeNT Projects, but this repository is no FreeNT Project. Beep-boop. Abort. Thanks for
            reading my comment. Beep-boop.
            
            <sub>Signed, NT BOT</sub>
